[2022-10-12T15:43:47.510-0500] {processor.py:156} INFO - Started process (PID=122013) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:43:47.511-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:43:47.512-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:43:47.512-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:43:47.516-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:43:47.513-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:43:47.517-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:43:47.537-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.030 seconds
[2022-10-12T15:44:17.715-0500] {processor.py:156} INFO - Started process (PID=122115) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:44:17.717-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:44:17.718-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:44:17.718-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:44:17.720-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:44:17.719-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:44:17.721-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:44:17.743-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.033 seconds
[2022-10-12T15:44:47.972-0500] {processor.py:156} INFO - Started process (PID=122210) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:44:47.977-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:44:47.980-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:44:47.979-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:44:47.989-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:44:47.985-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:44:47.990-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:44:48.021-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.065 seconds
[2022-10-12T15:45:18.287-0500] {processor.py:156} INFO - Started process (PID=122342) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:45:18.289-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:45:18.290-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:45:18.290-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:45:18.294-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:45:18.293-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:45:18.295-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:45:18.318-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.037 seconds
[2022-10-12T15:45:48.665-0500] {processor.py:156} INFO - Started process (PID=122442) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:45:48.671-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:45:48.674-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:45:48.673-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:45:48.684-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:45:48.680-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:45:48.686-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:45:48.733-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.080 seconds
[2022-10-12T15:46:19.007-0500] {processor.py:156} INFO - Started process (PID=122537) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:46:19.010-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:46:19.011-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:46:19.010-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:46:19.014-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:46:19.013-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:46:19.015-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:46:19.047-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.044 seconds
[2022-10-12T15:46:49.402-0500] {processor.py:156} INFO - Started process (PID=122628) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:46:49.442-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:46:49.443-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:46:49.443-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:46:49.446-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:46:49.445-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:46:49.446-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:46:49.469-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.070 seconds
[2022-10-12T15:47:19.652-0500] {processor.py:156} INFO - Started process (PID=122734) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:47:19.657-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:47:19.660-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:47:19.659-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:47:19.669-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:47:19.665-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:47:19.671-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:47:19.709-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.075 seconds
[2022-10-12T15:47:50.036-0500] {processor.py:156} INFO - Started process (PID=122837) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:47:50.075-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:47:50.076-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:47:50.076-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:47:50.079-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:47:50.078-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:47:50.080-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:47:50.100-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.067 seconds
[2022-10-12T15:48:20.384-0500] {processor.py:156} INFO - Started process (PID=122962) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:48:20.426-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:48:20.427-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:48:20.427-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:48:20.431-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:48:20.430-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:48:20.432-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:48:20.464-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.084 seconds
[2022-10-12T15:48:50.821-0500] {processor.py:156} INFO - Started process (PID=123130) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:48:50.825-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:48:50.828-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:48:50.828-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:48:50.836-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:48:50.833-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:48:50.837-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:48:50.887-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.073 seconds
[2022-10-12T15:49:21.181-0500] {processor.py:156} INFO - Started process (PID=123218) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:49:21.186-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:49:21.188-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:49:21.188-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:49:21.197-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:49:21.193-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:49:21.199-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:49:21.242-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.072 seconds
[2022-10-12T15:49:51.518-0500] {processor.py:156} INFO - Started process (PID=123315) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:49:51.520-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:49:51.521-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:49:51.521-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:49:51.524-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:49:51.523-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:49:51.525-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:49:51.551-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.037 seconds
[2022-10-12T15:50:22.002-0500] {processor.py:156} INFO - Started process (PID=123417) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:50:22.006-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:50:22.007-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:50:22.007-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:50:22.011-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:50:22.009-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:50:22.013-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:50:22.057-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.060 seconds
[2022-10-12T15:50:52.558-0500] {processor.py:156} INFO - Started process (PID=123519) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:50:52.562-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:50:52.563-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:50:52.563-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:50:52.570-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:50:52.567-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:50:52.571-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:50:52.623-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.074 seconds
[2022-10-12T15:51:23.072-0500] {processor.py:156} INFO - Started process (PID=123608) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:51:23.074-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:51:23.076-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:51:23.076-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:51:23.080-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:51:23.079-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:51:23.081-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:51:23.111-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.044 seconds
[2022-10-12T15:51:53.510-0500] {processor.py:156} INFO - Started process (PID=123711) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:51:53.512-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:51:53.513-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:51:53.513-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:51:53.519-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:51:53.517-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:51:53.519-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:51:53.553-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.048 seconds
[2022-10-12T15:52:23.940-0500] {processor.py:156} INFO - Started process (PID=123801) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:52:23.942-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:52:23.943-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:52:23.943-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:52:23.945-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:52:23.944-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:52:23.946-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:52:23.967-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.030 seconds
[2022-10-12T15:52:54.305-0500] {processor.py:156} INFO - Started process (PID=123898) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:52:54.307-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:52:54.308-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:52:54.308-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:52:54.311-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:52:54.309-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:52:54.311-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:52:54.398-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.099 seconds
[2022-10-12T15:53:24.567-0500] {processor.py:156} INFO - Started process (PID=123990) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:53:24.571-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:53:24.572-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:53:24.572-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:53:24.579-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:53:24.576-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:53:24.580-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:53:24.617-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.056 seconds
[2022-10-12T15:53:55.114-0500] {processor.py:156} INFO - Started process (PID=124144) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:53:55.116-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:53:55.116-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:53:55.116-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:53:55.119-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:53:55.118-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:53:55.119-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:53:55.148-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.038 seconds
[2022-10-12T15:54:25.509-0500] {processor.py:156} INFO - Started process (PID=124218) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:54:25.511-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:54:25.512-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:54:25.512-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:54:25.514-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:54:25.513-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:54:25.515-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:54:25.537-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.032 seconds
[2022-10-12T15:54:55.838-0500] {processor.py:156} INFO - Started process (PID=124324) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:54:55.842-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:54:55.844-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:54:55.843-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:54:55.852-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:54:55.848-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:54:55.853-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:54:55.907-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.079 seconds
[2022-10-12T15:55:26.295-0500] {processor.py:156} INFO - Started process (PID=124401) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:55:26.297-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:55:26.298-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:55:26.297-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:55:26.300-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:55:26.299-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:55:26.300-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:55:26.321-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.029 seconds
[2022-10-12T15:55:56.415-0500] {processor.py:156} INFO - Started process (PID=124502) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:55:56.417-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:55:56.418-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:55:56.417-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:55:56.420-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:55:56.419-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:55:56.420-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:55:56.439-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.030 seconds
[2022-10-12T15:56:26.860-0500] {processor.py:156} INFO - Started process (PID=124589) to work on /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:56:26.862-0500] {processor.py:758} INFO - Processing file /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py for tasks to queue
[2022-10-12T15:56:26.863-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:56:26.862-0500] {dagbag.py:525} INFO - Filling up the DagBag from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:56:26.866-0500] {logging_mixin.py:117} INFO - [2022-10-12T15:56:26.865-0500] {dagbag.py:330} ERROR - Failed to import: /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
Traceback (most recent call last):
  File "/home/gabsiston/Documentos/projetos/airflow-data/venv/lib/python3.8/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 981, in get_code
  File "<frozen importlib._bootstrap_external>", line 911, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py", line 15
    main(sys.argv[1:])
    ^
IndentationError: expected an indented block
[2022-10-12T15:56:26.866-0500] {processor.py:770} WARNING - No viable dags retrieved from /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py
[2022-10-12T15:56:26.890-0500] {processor.py:178} INFO - Processing /home/gabsiston/Documentos/projetos/airflow-data/dags/aa.py took 0.036 seconds
